In [1]:
import numpy as np

In [5]:
c=1,2,3,4
v=np.array(c)

In [6]:
v

array([1, 2, 3, 4])

In [8]:
np.vectorize(c)

In [9]:
np.angle(c)

array([0., 0., 0., 0.])

In [14]:
l=[[1,2,3],[5,6,7]]
c=np.array(l)

In [15]:
np.angle(c)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [70]:
a=[[[1,2,3],[4,5,6],[4,5,6]],[[7,8,9],[6,3,9],[11,12,13]]]
b=[[[4,5,6],[8,5,4],[8,4,1]],[[3,7,8],[9,4,5],[1,3,6]]]
A=np.array(a)
B=np.array(b)

In [71]:
A

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [ 6,  3,  9],
        [11, 12, 13]]])

In [72]:
A.ndim

3

In [73]:
B

array([[[4, 5, 6],
        [8, 5, 4],
        [8, 4, 1]],

       [[3, 7, 8],
        [9, 4, 5],
        [1, 3, 6]]])

In [74]:
B.ndim

3

In [78]:
np.dot(A,B)

array([[[[ 44,  27,  17],
         [ 24,  24,  36]],

        [[104,  69,  50],
         [ 63,  66,  93]],

        [[104,  69,  50],
         [ 63,  66,  93]]],


       [[[164, 111,  83],
         [102, 108, 150]],

        [[120,  81,  57],
         [ 54,  81, 117]],

        [[244, 167, 127],
         [154, 164, 226]]]])

In [75]:
np.cross(A,B)

array([[[ -3,   6,  -3],
        [-10,  32, -20],
        [-19,  44, -24]],

       [[  1, -29,  25],
        [-21,  51,  -3],
        [ 33, -53,  21]]])

In [76]:
np.cross(B,A)

array([[[  3,  -6,   3],
        [ 10, -32,  20],
        [ 19, -44,  24]],

       [[ -1,  29, -25],
        [ 21, -51,   3],
        [-33,  53, -21]]])

In [77]:
np.add(A,B)

array([[[ 5,  7,  9],
        [12, 10, 10],
        [12,  9,  7]],

       [[10, 15, 17],
        [15,  7, 14],
        [12, 15, 19]]])

In [62]:
a=([[1, 4], [5, 6]])
b=([[2, 4], [5, 2]]) 
A=np.array(a)
B=np.array(b)
A.dot(B)

array([[22, 12],
       [40, 32]])

In [80]:
a=np.random.randint(10,20,size=(3,3))
b=np.random.randint(50,60,size=(3,3))

In [65]:
a.dot(b)

array([[2516, 2401, 2379],
       [2384, 2283, 2289],
       [2842, 2715, 2704]])

In [68]:
np.cross(a,b)

array([[ 424, -341, -107],
       [  46,  149, -213],
       [ 401, -388,  -19]])

In [69]:
np.add(a,b)

array([[73, 71, 63],
       [71, 71, 65],
       [71, 70, 69]])